# This is a basic workflow to help you get started with Actions

name: Build TitleDB

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
  - cron: 0/5 * * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: arch-box/nut
      
      - name: Install Linux deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        env:
          USECURL: 7.79.0-openssl11-gssapi-libssh2
          USESSL: openssl
          USEOPENSSL: 1.1.1d
        with:
          packages: libcurl4-gnutls-dev libgnutls28-dev
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.9
          cache: 'pip'
      - run: |
          pip install -r requirements.txt
          pip install Werkzeug~=2.3.7
          


      # Runs a set of commands using the runners shell
      - name: Build TitleDB
        run: |
          rm -rf titledb
          git clone --depth 1 https://github.com/blawar/titledb titledb
          touch titledb/titles.json
          python3 nut.py -U --import-region US --language en
          cp titledb/titles.json ./titles.US.en.json

      - name: Compress TitleDB for use with Tinfoil as an index
        run: |
          (echo '{ "titledb": '; cat titles.US.en.json; echo "}") > titlesIndex.json
          # Workspace is overrided by arch-box/nut, so we need to wget the trim.py
          wget https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_REF_NAME}/trim.py -O trim.py
          python3 trim.py titlesIndex.json
          wget https://blawar.github.io/tinfoil/files/encrypt.py
          wget https://blawar.github.io/tinfoil/files/public.key
          python3 encrypt.py -i titlesIndex.json -o titles.tfl -k public.key --zstd

      - name: Compress TitleDB for use with Tinfoil as a db cache replacement
        run: |
          python3 encrypt.py -i titles.US.en.json -o titles.US.en.zstd.json --zstd
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: titledb # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ./titles.*
          # The desired behavior if no files are found using the provided path.
      
          if-no-files-found: error
          # Duration after which artifact will expire in days. 0 means using default retention.
          # Minimum 1 day. Maximum 90 days unless changed from the repository settings page.
      
          # retention-days: # optional
          
#      - name: git Actions
#        uses: srt32/git-actions@v0.0.3
#        with:
#          args: git commit; git push
#          
#      - name: Update repo
#        run: |
#          git commit
#          git push
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: latest
          title: Update TitleDB with workflow
          files: |
            titles.US.en.json
            titles.tfl
